CREATE TABLE Stores(
	StoreID INT NOT NULL AUTO_INCREMENT,
    City VARCHAR(50) NOT NULL,
    Phone BIGINT NOT NULL,
    PostalCode INT NOT NULL,
    
    PRIMARY KEY(StoreID)
    
)AUTO_INCREMENT = 1 ENGINE InnoDB;
